// import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata={title: "first project"}
//  Metadata = {
//   title: "first project",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav style={{width:"100%",background:"teal",fontFamily:"fantasy",fontSize:"30px",display:"flex" ,justifyContent:"center",alignItems:"center"}}>
          <Link style={{margin:"7px"}} href="/">
          page
          </Link>
          <Link style={{margin:"7px"}} href="/page1">
          page1
          </Link>
          <Link style={{margin:"7px"}} href="/page2">
          page2
          </Link>
          <Link style={{margin:"7px"}} href="/page3">
          page3
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}